/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalkIndexRouteImport } from './routes/talk.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as TalkThreadIdRouteImport } from './routes/talk.$threadId'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiQwenProofRouteImport } from './routes/api/qwen-proof'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkIndexRoute = TalkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalkRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const TalkThreadIdRoute = TalkThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => TalkRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQwenProofRoute = ApiQwenProofRouteImport.update({
  id: '/api/qwen-proof',
  path: '/api/qwen-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/talk': typeof TalkRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/qwen-proof': typeof ApiQwenProofRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/talk/$threadId': typeof TalkThreadIdRoute
  '/doctor/': typeof DoctorIndexRoute
  '/talk/': typeof TalkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/caregiver': typeof CaregiverRoute
  '/emergency': typeof EmergencyRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/qwen-proof': typeof ApiQwenProofRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/talk/$threadId': typeof TalkThreadIdRoute
  '/doctor': typeof DoctorIndexRoute
  '/talk': typeof TalkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/talk': typeof TalkRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/qwen-proof': typeof ApiQwenProofRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/talk/$threadId': typeof TalkThreadIdRoute
  '/doctor/': typeof DoctorIndexRoute
  '/talk/': typeof TalkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/caregiver'
    | '/doctor'
    | '/emergency'
    | '/memory'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/talk'
    | '/api/health'
    | '/api/qwen-proof'
    | '/api/stt'
    | '/api/tts'
    | '/talk/$threadId'
    | '/doctor/'
    | '/talk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/caregiver'
    | '/emergency'
    | '/memory'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/api/health'
    | '/api/qwen-proof'
    | '/api/stt'
    | '/api/tts'
    | '/talk/$threadId'
    | '/doctor'
    | '/talk'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/caregiver'
    | '/doctor'
    | '/emergency'
    | '/memory'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/talk'
    | '/api/health'
    | '/api/qwen-proof'
    | '/api/stt'
    | '/api/tts'
    | '/talk/$threadId'
    | '/doctor/'
    | '/talk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CaregiverRoute: typeof CaregiverRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  EmergencyRoute: typeof EmergencyRoute
  MemoryRoute: typeof MemoryRoute
  ProfileRoute: typeof ProfileRoute
  RemindersRoute: typeof RemindersRoute
  SymptomsRoute: typeof SymptomsRoute
  TalkRoute: typeof TalkRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQwenProofRoute: typeof ApiQwenProofRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk/': {
      id: '/talk/'
      path: '/'
      fullPath: '/talk/'
      preLoaderRoute: typeof TalkIndexRouteImport
      parentRoute: typeof TalkRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/talk/$threadId': {
      id: '/talk/$threadId'
      path: '/$threadId'
      fullPath: '/talk/$threadId'
      preLoaderRoute: typeof TalkThreadIdRouteImport
      parentRoute: typeof TalkRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qwen-proof': {
      id: '/api/qwen-proof'
      path: '/api/qwen-proof'
      fullPath: '/api/qwen-proof'
      preLoaderRoute: typeof ApiQwenProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DoctorRouteChildren {
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface TalkRouteChildren {
  TalkThreadIdRoute: typeof TalkThreadIdRoute
  TalkIndexRoute: typeof TalkIndexRoute
}

const TalkRouteChildren: TalkRouteChildren = {
  TalkThreadIdRoute: TalkThreadIdRoute,
  TalkIndexRoute: TalkIndexRoute,
}

const TalkRouteWithChildren = TalkRoute._addFileChildren(TalkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CaregiverRoute: CaregiverRoute,
  DoctorRoute: DoctorRouteWithChildren,
  EmergencyRoute: EmergencyRoute,
  MemoryRoute: MemoryRoute,
  ProfileRoute: ProfileRoute,
  RemindersRoute: RemindersRoute,
  SymptomsRoute: SymptomsRoute,
  TalkRoute: TalkRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiQwenProofRoute: ApiQwenProofRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
